// "So geht's", Kapitel "Einkaufslisten": Bereich "Einkaufslisten" der App (Stand 0.14.3).
import { foto, link } from './hilfen.mjs';

export default {
  slug: 'einkaufslisten',
  titel: 'Einkaufslisten',
  kurz: 'Aufschreiben, abhaken, sortieren, teilen und in die Liste scannen.',
  vorspann: 'Listen anlegen, aufschreiben, was du brauchst, im Laden abhaken und die Liste als Text teilen.',
  film: { datei: 'auf-die-liste', alt: 'Auf der Produktseite wird „Auf die Liste“ angetippt, die Seite meldet „Auf ‚Wocheneinkauf‘ gesetzt“, dann steht das Produkt auf der Einkaufsliste „Wocheneinkauf“ mit ihren Warengruppen.', unterschrift: 'Von der Produktkarte auf die Liste' },
  teile: [
    {
      titel: 'Liste anlegen',
      anker: 'liste-anlegen',
      funktionen: ['LISTE-01'],
      nutzen: 'Du legst eine oder mehrere Einkaufslisten an, ganz ohne Scannen, zum Beispiel eine für den Wocheneinkauf und eine für das Fest am Wochenende.',
      wo: 'Listen > „Liste anlegen“, bei jeder weiteren „Neue Liste“',
      fotos: [foto('liste_anlegen_03', 'Die Übersicht „Deine Listen“')],
    },
    {
      titel: 'Einträge hinzufügen',
      anker: 'eintraege-hinzufuegen',
      funktionen: ['LISTE-02'],
      nutzen: 'Du schreibst auf, was du brauchst, zum Beispiel „2 Zwiebeln“ oder „500 g Mehl“. Das Feld bleibt offen für den nächsten Eintrag.',
      wo: 'Listen > Liste öffnen > Feld „Hinzufügen“',
      fotos: [foto('liste_eintraege_02', '„2 Zwiebeln“ wird getippt')],
    },
    {
      titel: 'Vorschläge beim Tippen',
      anker: 'vorschlaege',
      funktionen: ['LISTE-03'],
      nutzen: 'Beim Tippen schlägt FoodAsu passende Wörter vor, auch solche, die du schon einmal aufgeschrieben hast. Ein Tipp setzt den Vorschlag auf die Liste.',
      wo: 'Liste > Feld „Hinzufügen“, beim Tippen',
      verweis: link('Die gemerkten Wörter entfernst du in den Einstellungen: ', 'Löschen', '/so-gehts/deine-daten/#loeschen'),
    },
    {
      titel: 'Abhaken',
      anker: 'abhaken',
      funktionen: ['LISTE-04'],
      nutzen: 'Im Laden hakst du jeden Eintrag mit einem Tipp ab. Erledigtes rutscht nach unten in den Bereich „Erledigt“; oben bleibt, was noch fehlt.',
      wo: 'Liste > Kästchen links am Eintrag',
      fotos: [foto('liste_abhaken_02', 'Abgehakt, mit „Rückgängig“')],
      verweis: link('Der ganze Weg von zu Hause bis in den Laden steht auf einer eigenen Seite: ', 'Zu Hause schreiben, im Laden abhaken', '/so-gehts/zu-hause-schreiben-im-laden-abhaken/'),
    },
    {
      titel: 'Warengruppen',
      anker: 'warengruppen',
      funktionen: ['LISTE-05'],
      nutzen: 'Die Liste ordnet sich von selbst nach Warengruppen wie im Laden. So gehst du Gruppe für Gruppe durch und musst nicht zurücklaufen.',
      wo: 'Liste; die Gruppe eines Eintrags änderst du unter „Eintrag bearbeiten“',
      fotos: [foto('liste_warengruppen_01', 'Einträge unter ihrer Warengruppe')],
    },
    {
      titel: 'Eintrag bearbeiten',
      anker: 'eintrag-bearbeiten',
      funktionen: ['LISTE-06'],
      nutzen: 'Du änderst Name, Menge, Einheit, Notiz und Warengruppe eines Eintrags.',
      wo: 'Liste > Eintrag antippen; bei einem gescannten Produkt die Menge rechts antippen',
      fotos: [foto('liste_bearbeiten_01', '„Eintrag bearbeiten“')],
    },
    {
      titel: 'Eintrag löschen',
      anker: 'eintrag-loeschen',
      funktionen: ['LISTE-07'],
      nutzen: 'Du entfernst einen Eintrag mit einem Wisch. „Rückgängig“ holt ihn kurz danach zurück.',
      wo: 'Liste > Eintrag zur Seite wischen',
    },
    {
      titel: 'Gleiche Einträge',
      anker: 'gleiche-eintraege',
      funktionen: ['LISTE-08'],
      nutzen: 'Setzt du etwas auf die Liste, das schon darauf steht, zählt FoodAsu die Menge zusammen oder sagt dir, dass es schon dasteht.',
      wo: 'Liste, beim Hinzufügen',
    },
    {
      titel: 'Erledigte löschen',
      anker: 'erledigte-loeschen',
      funktionen: ['LISTE-09'],
      nutzen: 'Nach dem Einkauf räumst du alle abgehakten Einträge auf einmal weg. Was offen ist, bleibt für den nächsten Einkauf stehen.',
      wo: 'Liste > „Weitere Aktionen“ (drei Punkte) > „Erledigte löschen“',
    },
    {
      titel: 'Liste umbenennen oder löschen',
      anker: 'liste-umbenennen-oder-loeschen',
      funktionen: ['LISTE-10'],
      nutzen: 'Du gibst einer Liste einen anderen Namen oder löschst sie samt ihren Einträgen. Löschen lässt sich nicht rückgängig machen.',
      wo: 'Listen > drei Punkte an der Karte der Liste > „Umbenennen“ oder „Löschen“',
    },
    {
      titel: 'Als Text teilen',
      anker: 'als-text-teilen',
      funktionen: ['LISTE-11'],
      nutzen: 'Du schickst die offenen Einträge einer Liste als Text an eine App deiner Wahl, zum Beispiel an jemanden, der einkaufen geht. Was dein Haushalt meidet, steht nicht im Text.',
      wo: 'Liste > „Weitere Aktionen“ (drei Punkte) > „Als Text teilen“',
      fotos: [foto('liste_erledigte_loeschen_01', 'Das Menü der Liste')],
    },
    {
      titel: 'Hinweise auf der Liste',
      anker: 'hinweise-auf-der-liste',
      funktionen: ['LISTE-12'],
      nutzen: 'Bei einem Eintrag steht, wen im Haushalt er betrifft. Das ist ein Hinweis, kein Urteil: Ein Urteil gibt es nur bei gescannten Produkten.',
      wo: 'Liste > unter dem Eintrag',
      fotos: [foto('liste_hinweise_01', 'Hinweise unter den Einträgen')],
    },
    {
      titel: 'In die Liste scannen',
      anker: 'in-die-liste-scannen',
      funktionen: ['LISTE-13'],
      nutzen: 'Du öffnest den Scanner für eine bestimmte Liste, und jedes gescannte Produkt kommt direkt darauf.',
      wo: 'Liste > Scan-Knopf rechts im Feld „Hinzufügen“',
      verweis: link('Von jeder Produktkarte aus geht es auch: ', '„Auf die Liste“', '/so-gehts/produktkarte/#auf-die-liste'),
    },
    {
      titel: 'Produkt ansehen',
      anker: 'produkt-ansehen',
      funktionen: ['LISTE-16'],
      nutzen: 'Ein Tipp auf ein gescanntes Produkt in der Liste öffnet seine Produktkarte mit dem Urteil für deinen Haushalt.',
      wo: 'Liste > Name des Produkts antippen',
    },
    {
      titel: '„Was kann ich damit kochen?“',
      anker: 'was-kann-ich-damit-kochen',
      alteAnker: ['vom-einkauf-zum-kochen'],
      funktionen: ['LISTE-14'],
      nutzen: 'FoodAsu zeigt dir Rezepte, für die schon vieles auf deiner Liste steht, und sagt, was noch fehlt. Das Fehlende setzt du mit einem Tipp dazu.',
      wo: 'Liste > „Was kann ich damit kochen?“',
      fotos: [foto('liste_kochen_01', 'Rezepte zur Liste')],
    },
    {
      titel: 'Die Liste eines Rezepts',
      anker: 'liste-eines-rezepts',
      funktionen: ['LISTE-15'],
      nutzen: 'Eine Liste, die aus einem Rezept entstanden ist, heißt wie das Rezept und führt mit einem Tipp dorthin zurück.',
      wo: 'Listen > Liste mit dem Namen des Rezepts > erste Zeile',
      fotos: [foto('liste_rezeptliste_01', 'Die Liste zum Rezept „Pizza Margherita“', 'Liste „Pizza Margherita“ in FoodAsu: oben die Zeile, die das Rezept nennt, darunter die Zutaten mit ihrer Menge.')],
      verweis: link('Wie eine solche Liste entsteht, steht im Kapitel „Rezepte“: ', 'Fehlende Zutaten auf die Liste', '/so-gehts/rezepte/#fehlende-zutaten-auf-die-liste'),
    },
  ],
  verweise: [
    { text: 'Zu Hause schreiben, im Laden abhaken', ziel: '/so-gehts/zu-hause-schreiben-im-laden-abhaken/' },
    { text: 'Rezepte', ziel: '/so-gehts/rezepte/' },
    { text: 'Die Produktkarte', ziel: '/so-gehts/produktkarte/' },
  ],
};
