// "So geht's", Kapitel "Die Produktkarte": Bereich "Produktkarte und Urteil" der App ohne das Urteil selbst
// (Stand 0.14.3). Das Urteil steht im Kapitel "Scannen und das Urteil verstehen".
import { foto, link } from './hilfen.mjs';

export default {
  slug: 'produktkarte',
  symbol: 'etikett',
  leitbild: 'scanner_mehrere_01',
  titel: 'Die Produktkarte',
  kurz: 'Nährwerte, Abzeichen, Zutaten und „Auf die Liste“.',
  vorspann: 'Was auf der Produktkarte steht und was du von dort aus tun kannst.',
  teile: [
    {
      titel: 'Die Karte im Überblick',
      anker: 'ueberblick',
      symbol: 'etikett',
      gross: true,
      fotos: [foto('scanner_mehrere_01', 'Die Produktkarte, ganz geöffnet')],
      absaetze: [
        'Die Produktkarte erscheint nach einem Scan und wenn du ein Produkt aus „Zuletzt gescannt“ oder aus einer Liste öffnest. Oben steht das Urteil für deinen Haushalt, darunter folgen Nährwerte, Abzeichen und Zutaten, soweit sie in den Daten stehen.',
      ],
      verweis: link('Wie du das Urteil liest, steht im Kapitel „Scannen und das Urteil verstehen“: ', 'Das Urteil für den Haushalt', '/so-gehts/scannen-und-urteil/#das-urteil'),
    },
    {
      titel: 'Nährwerte, Zucker, Nutri-Score und Verarbeitung',
      anker: 'naehrwerte',
      symbol: 'diagramm',
      funktionen: ['KARTE-04'],
      nutzen: 'Du siehst auf einen Blick Kalorien, Zucker, Fett, Salz, den Nutri-Score und den Grad der Verarbeitung, weiter unten weitere Nährwerte. Fehlt ein Wert, steht dort „keine Angabe“.',
      wo: 'Produktkarte > Kacheln unter dem Urteil',
    },
    {
      titel: 'Abzeichen',
      anker: 'abzeichen',
      symbol: 'blatt',
      funktionen: ['KARTE-05'],
      nutzen: 'Kleine Abzeichen sagen, ob das Produkt laut Daten vegetarisch oder vegan ist, ob Palmöl drin ist und wie viele Zusatzstoffe es hat.',
      wo: 'Produktkarte nach oben ziehen > Abzeichen unter den Kacheln',
      fotos: [foto('karte_abzeichen_01', 'Abzeichen, darunter die Zutaten')],
    },
    {
      titel: 'Zutaten',
      anker: 'zutaten',
      symbol: 'liste',
      funktionen: ['KARTE-06'],
      nutzen: 'Du liest die Zutaten des Produkts, so wie sie in den Daten stehen.',
      wo: 'Produktkarte nach oben ziehen > „Zutaten“',
    },
    {
      titel: 'Stand und Quelle der Daten',
      anker: 'stand-der-daten',
      symbol: 'datenbank',
      funktionen: ['KARTE-10'],
      nutzen: 'Die Karte sagt, von wann die Angaben sind und woher sie stammen: „Daten: Open Food Facts“. Findet FoodAsu ein Produkt nicht oder besteht keine Verbindung, steht das anstelle der Karte da.',
      wo: 'Produktkarte nach oben ziehen > unter den Zutaten',
      verweis: link('Fehlt ein Produkt in den Daten, kannst du es selbst ergänzen: ', 'Fehlt ein Produkt?', '/so-gehts/deine-daten/#fehlt-ein-produkt'),
    },
    {
      titel: '„Daten neu laden“',
      anker: 'daten-neu-laden',
      symbol: 'neu',
      funktionen: ['KARTE-08'],
      nutzen: 'Du holst die Angaben zu einem Produkt noch einmal frisch von Open Food Facts, etwa wenn dort etwas ergänzt wurde.',
      wo: 'Produktkarte > „Weitere Aktionen“ (drei Punkte) > „Daten neu laden“',
    },
    {
      titel: 'Eigener Name für ein Produkt',
      anker: 'eigener-name',
      symbol: 'stift',
      funktionen: ['KARTE-07'],
      nutzen: 'Du gibst einem Produkt einen eigenen Namen, zum Beispiel wenn der Name in den Daten fehlt oder zu lang ist, und stellst das Original wieder her.',
      wo: 'Produktkarte nach oben ziehen > ganz unten „Name ändern“',
    },
    {
      titel: 'Produktbild groß',
      anker: 'produktbild',
      symbol: 'bild',
      funktionen: ['KARTE-11'],
      nutzen: 'Ein Tipp auf das kleine Produktbild zeigt es groß.',
      wo: 'Produktkarte > Produktbild antippen',
    },
    {
      titel: '„Auf die Liste“',
      anker: 'auf-die-liste',
      symbol: 'plus',
      gross: true,
      funktionen: ['KARTE-09'],
      nutzen: 'Du setzt ein Produkt mit einem Tipp auf eine Einkaufsliste und wählst Liste und Stückzahl. „Rückgängig“ nimmt es gleich wieder herunter.',
      wo: 'Produktkarte > Leiste unten > „Auf die Liste“',
      fotos: [foto('karte_auf_die_liste_02', 'Auf die Liste gesetzt, mit „Rückgängig“')],
    },
  ],
  verweise: [
    { text: 'Scannen und das Urteil verstehen', ziel: '/so-gehts/scannen-und-urteil/' },
    { text: 'Einkaufslisten', ziel: '/so-gehts/einkaufslisten/' },
  ],
};
